# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: d2ggamvr8msj74
  username: gqgkgzhihnuzuw
  password: 47d061d0865601e2170a7b6cbfac5274e7f76a937326ad524f0ab6990aeab693
  host: ec2-23-21-96-70.compute-1.amazonaws.com
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: d2ggamvr8msj74
  username: gqgkgzhihnuzuw
  password: 47d061d0865601e2170a7b6cbfac5274e7f76a937326ad524f0ab6990aeab693
  host: ec2-23-21-96-70.compute-1.amazonaws.com
  port: 5432
  
production:
  adapter: postgresql
  encoding: utf8
  database: d2ggamvr8msj74
  username: gqgkgzhihnuzuw
  password: 47d061d0865601e2170a7b6cbfac5274e7f76a937326ad524f0ab6990aeab693
  host: ec2-23-21-96-70.compute-1.amazonaws.com
  port: 5432
